// Bangladesh Districts Data
export const districtsByDivision = {
  "": [],
  Dhaka: [
    { value: "", label: "Select District" },
    { value: "Dhaka", label: "Dhaka" },
    { value: "Faridpur", label: "Faridpur" },
    { value: "Gazipur", label: "Gazipur" },
    { value: "Gopalganj", label: "Gopalganj" },
    { value: "Kishoreganj", label: "Kishoreganj" },
    { value: "Madaripur", label: "Madaripur" },
    { value: "Manikganj", label: "Manikganj" },
    { value: "Munshiganj", label: "Munshiganj" },
    { value: "Narayanganj", label: "Narayanganj" },
    { value: "Narsingdi", label: "Narsingdi" },
    { value: "Rajbari", label: "Rajbari" },
    { value: "Shariatpur", label: "Shariatpur" },
    { value: "Tangail", label: "Tangail" },
  ],
  Chittagong: [
    { value: "", label: "Select District" },
    { value: "Chittagong", label: "Chittagong" },
    { value: "Bandarban", label: "Bandarban" },
    { value: "Brahmanbaria", label: "Brahmanbaria" },
    { value: "Chandpur", label: "Chandpur" },
    { value: "Comilla", label: "Comilla" },
    { value: "Cox's Bazar", label: "Cox's Bazar" },
    { value: "Feni", label: "Feni" },
    { value: "Khagrachhari", label: "Khagrachhari" },
    { value: "Lakshmipur", label: "Lakshmipur" },
    { value: "Noakhali", label: "Noakhali" },
    { value: "Rangamati", label: "Rangamati" },
  ],
  Rajshahi: [
    { value: "", label: "Select District" },
    { value: "Rajshahi", label: "Rajshahi" },
    { value: "Bogra", label: "Bogra" },
    { value: "Joypurhat", label: "Joypurhat" },
    { value: "Naogaon", label: "Naogaon" },
    { value: "Natore", label: "Natore" },
    { value: "Chapainawabganj", label: "Chapainawabganj" },
    { value: "Pabna", label: "Pabna" },
    { value: "Sirajganj", label: "Sirajganj" },
  ],
  Khulna: [
    { value: "", label: "Select District" },
    { value: "Khulna", label: "Khulna" },
    { value: "Bagerhat", label: "Bagerhat" },
    { value: "Chuadanga", label: "Chuadanga" },
    { value: "Jessore", label: "Jessore" },
    { value: "Jhenaidah", label: "Jhenaidah" },
    { value: "Kushtia", label: "Kushtia" },
    { value: "Magura", label: "Magura" },
    { value: "Meherpur", label: "Meherpur" },
    { value: "Narail", label: "Narail" },
    { value: "Satkhira", label: "Satkhira" },
  ],
  Barisal: [
    { value: "", label: "Select District" },
    { value: "Barisal", label: "Barisal" },
    { value: "Barguna", label: "Barguna" },
    { value: "Bhola", label: "Bhola" },
    { value: "Jhalokati", label: "Jhalokati" },
    { value: "Patuakhali", label: "Patuakhali" },
    { value: "Pirojpur", label: "Pirojpur" },
  ],
  Sylhet: [
    { value: "", label: "Select District" },
    { value: "Sylhet", label: "Sylhet" },
    { value: "Habiganj", label: "Habiganj" },
    { value: "Moulvibazar", label: "Moulvibazar" },
    { value: "Sunamganj", label: "Sunamganj" },
  ],
  Rangpur: [
    { value: "", label: "Select District" },
    { value: "Rangpur", label: "Rangpur" },
    { value: "Dinajpur", label: "Dinajpur" },
    { value: "Gaibandha", label: "Gaibandha" },
    { value: "Kurigram", label: "Kurigram" },
    { value: "Lalmonirhat", label: "Lalmonirhat" },
    { value: "Nilphamari", label: "Nilphamari" },
    { value: "Panchagarh", label: "Panchagarh" },
    { value: "Thakurgaon", label: "Thakurgaon" },
  ],
  Mymensingh: [
    { value: "", label: "Select District" },
    { value: "Mymensingh", label: "Mymensingh" },
    { value: "Jamalpur", label: "Jamalpur" },
    { value: "Netrokona", label: "Netrokona" },
    { value: "Sherpur", label: "Sherpur" },
  ],
  International: [
    { value: "", label: "Select Country" },
    { value: "Any International", label: "Any International" },
    // North America
    { value: "USA", label: "United States" },
    { value: "Canada", label: "Canada" },
    { value: "Mexico", label: "Mexico" },
    // Europe
    { value: "UK", label: "United Kingdom" },
    { value: "Germany", label: "Germany" },
    { value: "France", label: "France" },
    { value: "Italy", label: "Italy" },
    { value: "Spain", label: "Spain" },
    { value: "Netherlands", label: "Netherlands" },
    { value: "Sweden", label: "Sweden" },
    { value: "Norway", label: "Norway" },
    { value: "Denmark", label: "Denmark" },
    { value: "Finland", label: "Finland" },
    { value: "Belgium", label: "Belgium" },
    { value: "Austria", label: "Austria" },
    { value: "Switzerland", label: "Switzerland" },
    { value: "Poland", label: "Poland" },
    { value: "Russia", label: "Russia" },
    { value: "Turkey", label: "Turkey" },
    // Oceania
    { value: "Australia", label: "Australia" },
    { value: "New Zealand", label: "New Zealand" },
    // Asia
    { value: "Japan", label: "Japan" },
    { value: "South Korea", label: "South Korea" },
    { value: "China", label: "China" },
    { value: "Singapore", label: "Singapore" },
    { value: "Thailand", label: "Thailand" },
    { value: "Indonesia", label: "Indonesia" },
    { value: "Philippines", label: "Philippines" },
    { value: "Vietnam", label: "Vietnam" },
    { value: "UAE", label: "United Arab Emirates" },
    { value: "Saudi Arabia", label: "Saudi Arabia" },
    { value: "Qatar", label: "Qatar" },
    { value: "Kuwait", label: "Kuwait" },
    { value: "Bahrain", label: "Bahrain" },
    { value: "Oman", label: "Oman" },
    { value: "Malaysia", label: "Malaysia" },
    { value: "Hong Kong", label: "Hong Kong" },
    { value: "Taiwan", label: "Taiwan" },
    // South Asia
    { value: "India", label: "India" },
    { value: "Pakistan", label: "Pakistan" },
    { value: "Sri Lanka", label: "Sri Lanka" },
    { value: "Nepal", label: "Nepal" },
    { value: "Bhutan", label: "Bhutan" },
    { value: "Maldives", label: "Maldives" },
    // Africa
    { value: "South Africa", label: "South Africa" },
    { value: "Egypt", label: "Egypt" },
    { value: "Nigeria", label: "Nigeria" },
    { value: "Kenya", label: "Kenya" },
    { value: "Ghana", label: "Ghana" },
    { value: "Ethiopia", label: "Ethiopia" },
    { value: "Morocco", label: "Morocco" },
    { value: "Tunisia", label: "Tunisia" },
    // South America
    { value: "Brazil", label: "Brazil" },
    { value: "Argentina", label: "Argentina" },
    { value: "Chile", label: "Chile" },
    { value: "Colombia", label: "Colombia" },
    { value: "Peru", label: "Peru" },
    { value: "Venezuela", label: "Venezuela" },
    { value: "Uruguay", label: "Uruguay" },
    { value: "Other", label: "Other Country" },
  ],
};
