// Bangladesh Districts Data
export const districtsByDivision = {
  "": [],
  Dhaka: [
    { value: "", label: "Select District" },
    { value: "Dhaka", label: "Dhaka" },
    { value: "Faridpur", label: "Faridpur" },
    { value: "Gazipur", label: "Gazipur" },
    { value: "Gopalganj", label: "Gopalganj" },
    { value: "Kishoreganj", label: "Kishoreganj" },
    { value: "Madaripur", label: "Madaripur" },
    { value: "Manikganj", label: "Manikganj" },
    { value: "Munshiganj", label: "Munshiganj" },
    { value: "Narayanganj", label: "Narayanganj" },
    { value: "Narsingdi", label: "Narsingdi" },
    { value: "Rajbari", label: "Rajbari" },
    { value: "Shariatpur", label: "Shariatpur" },
    { value: "Tangail", label: "Tangail" },
  ],
  Chittagong: [
    { value: "", label: "Select District" },
    { value: "Chittagong", label: "Chittagong" },
    { value: "Bandarban", label: "Bandarban" },
    { value: "Brahmanbaria", label: "Brahmanbaria" },
    { value: "Chandpur", label: "Chandpur" },
    { value: "Comilla", label: "Comilla" },
    { value: "Cox's Bazar", label: "Cox's Bazar" },
    { value: "Feni", label: "Feni" },
    { value: "Khagrachhari", label: "Khagrachhari" },
    { value: "Lakshmipur", label: "Lakshmipur" },
    { value: "Noakhali", label: "Noakhali" },
    { value: "Rangamati", label: "Rangamati" },
  ],
  Rajshahi: [
    { value: "", label: "Select District" },
    { value: "Rajshahi", label: "Rajshahi" },
    { value: "Bogra", label: "Bogra" },
    { value: "Joypurhat", label: "Joypurhat" },
    { value: "Naogaon", label: "Naogaon" },
    { value: "Natore", label: "Natore" },
    { value: "Chapainawabganj", label: "Chapainawabganj" },
    { value: "Pabna", label: "Pabna" },
    { value: "Sirajganj", label: "Sirajganj" },
  ],
  Khulna: [
    { value: "", label: "Select District" },
    { value: "Khulna", label: "Khulna" },
    { value: "Bagerhat", label: "Bagerhat" },
    { value: "Chuadanga", label: "Chuadanga" },
    { value: "Jessore", label: "Jessore" },
    { value: "Jhenaidah", label: "Jhenaidah" },
    { value: "Kushtia", label: "Kushtia" },
    { value: "Magura", label: "Magura" },
    { value: "Meherpur", label: "Meherpur" },
    { value: "Narail", label: "Narail" },
    { value: "Satkhira", label: "Satkhira" },
  ],
  Barisal: [
    { value: "", label: "Select District" },
    { value: "Barisal", label: "Barisal" },
    { value: "Barguna", label: "Barguna" },
    { value: "Bhola", label: "Bhola" },
    { value: "Jhalokati", label: "Jhalokati" },
    { value: "Patuakhali", label: "Patuakhali" },
    { value: "Pirojpur", label: "Pirojpur" },
  ],
  Sylhet: [
    { value: "", label: "Select District" },
    { value: "Sylhet", label: "Sylhet" },
    { value: "Habiganj", label: "Habiganj" },
    { value: "Moulvibazar", label: "Moulvibazar" },
    { value: "Sunamganj", label: "Sunamganj" },
  ],
  Rangpur: [
    { value: "", label: "Select District" },
    { value: "Rangpur", label: "Rangpur" },
    { value: "Dinajpur", label: "Dinajpur" },
    { value: "Gaibandha", label: "Gaibandha" },
    { value: "Kurigram", label: "Kurigram" },
    { value: "Lalmonirhat", label: "Lalmonirhat" },
    { value: "Nilphamari", label: "Nilphamari" },
    { value: "Panchagarh", label: "Panchagarh" },
    { value: "Thakurgaon", label: "Thakurgaon" },
  ],
  Mymensingh: [
    { value: "", label: "Select District" },
    { value: "Mymensingh", label: "Mymensingh" },
    { value: "Jamalpur", label: "Jamalpur" },
    { value: "Netrokona", label: "Netrokona" },
    { value: "Sherpur", label: "Sherpur" },
  ],
  International: [
    { value: "", label: "Select Country" },
    { value: "Any International", label: "Any International" },
  ],
};
