// Bangladesh Location Data Structure
export const divisions = [
  { value: "", label: "Select Division" },
  { value: "Dhaka", label: "Dhaka Division" },
  { value: "Chittagong", label: "Chittagong Division" },
  { value: "Rajshahi", label: "Rajshahi Division" },
  { value: "Khulna", label: "Khulna Division" },
  { value: "Barisal", label: "Barisal Division" },
  { value: "Sylhet", label: "Sylhet Division" },
  { value: "Rangpur", label: "Rangpur Division" },
  { value: "Mymensingh", label: "Mymensingh Division" },
  { value: "International", label: "International" },
];

export const districtsByDivision = {
  "": [],
  Dhaka: [
    { value: "", label: "Select District" },
    { value: "Dhaka", label: "Dhaka" },
    { value: "Faridpur", label: "Faridpur" },
    { value: "Gazipur", label: "Gazipur" },
    { value: "Gopalganj", label: "Gopalganj" },
    { value: "Kishoreganj", label: "Kishoreganj" },
    { value: "Madaripur", label: "Madaripur" },
    { value: "Manikganj", label: "Manikganj" },
    { value: "Munshiganj", label: "Munshiganj" },
    { value: "Narayanganj", label: "Narayanganj" },
    { value: "Narsingdi", label: "Narsingdi" },
    { value: "Rajbari", label: "Rajbari" },
    { value: "Shariatpur", label: "Shariatpur" },
    { value: "Tangail", label: "Tangail" },
  ],
  Chittagong: [
    { value: "", label: "Select District" },
    { value: "Chittagong", label: "Chittagong" },
    { value: "Bandarban", label: "Bandarban" },
    { value: "Brahmanbaria", label: "Brahmanbaria" },
    { value: "Chandpur", label: "Chandpur" },
    { value: "Comilla", label: "Comilla" },
    { value: "Cox's Bazar", label: "Cox's Bazar" },
    { value: "Feni", label: "Feni" },
    { value: "Khagrachhari", label: "Khagrachhari" },
    { value: "Lakshmipur", label: "Lakshmipur" },
    { value: "Noakhali", label: "Noakhali" },
    { value: "Rangamati", label: "Rangamati" },
  ],
  Rajshahi: [
    { value: "", label: "Select District" },
    { value: "Rajshahi", label: "Rajshahi" },
    { value: "Bogra", label: "Bogra" },
    { value: "Joypurhat", label: "Joypurhat" },
    { value: "Naogaon", label: "Naogaon" },
    { value: "Natore", label: "Natore" },
    { value: "Chapainawabganj", label: "Chapainawabganj" },
    { value: "Pabna", label: "Pabna" },
    { value: "Sirajganj", label: "Sirajganj" },
  ],
  Khulna: [
    { value: "", label: "Select District" },
    { value: "Khulna", label: "Khulna" },
    { value: "Bagerhat", label: "Bagerhat" },
    { value: "Chuadanga", label: "Chuadanga" },
    { value: "Jessore", label: "Jessore" },
    { value: "Jhenaidah", label: "Jhenaidah" },
    { value: "Kushtia", label: "Kushtia" },
    { value: "Magura", label: "Magura" },
    { value: "Meherpur", label: "Meherpur" },
    { value: "Narail", label: "Narail" },
    { value: "Satkhira", label: "Satkhira" },
  ],
  Barisal: [
    { value: "", label: "Select District" },
    { value: "Barisal", label: "Barisal" },
    { value: "Barguna", label: "Barguna" },
    { value: "Bhola", label: "Bhola" },
    { value: "Jhalokati", label: "Jhalokati" },
    { value: "Patuakhali", label: "Patuakhali" },
    { value: "Pirojpur", label: "Pirojpur" },
  ],
  Sylhet: [
    { value: "", label: "Select District" },
    { value: "Sylhet", label: "Sylhet" },
    { value: "Habiganj", label: "Habiganj" },
    { value: "Moulvibazar", label: "Moulvibazar" },
    { value: "Sunamganj", label: "Sunamganj" },
  ],
  Rangpur: [
    { value: "", label: "Select District" },
    { value: "Rangpur", label: "Rangpur" },
    { value: "Dinajpur", label: "Dinajpur" },
    { value: "Gaibandha", label: "Gaibandha" },
    { value: "Kurigram", label: "Kurigram" },
    { value: "Lalmonirhat", label: "Lalmonirhat" },
    { value: "Nilphamari", label: "Nilphamari" },
    { value: "Panchagarh", label: "Panchagarh" },
    { value: "Thakurgaon", label: "Thakurgaon" },
  ],
  Mymensingh: [
    { value: "", label: "Select District" },
    { value: "Mymensingh", label: "Mymensingh" },
    { value: "Jamalpur", label: "Jamalpur" },
    { value: "Netrakona", label: "Netrakona" },
    { value: "Sherpur", label: "Sherpur" },
  ],
  International: [
    { value: "", label: "Select Country" },
    { value: "Afghanistan", label: "Afghanistan" },
    { value: "Albania", label: "Albania" },
    { value: "Algeria", label: "Algeria" },
    { value: "Andorra", label: "Andorra" },
    { value: "Angola", label: "Angola" },
    { value: "Antigua and Barbuda", label: "Antigua and Barbuda" },
    { value: "Argentina", label: "Argentina" },
    { value: "Armenia", label: "Armenia" },
    { value: "Australia", label: "Australia" },
    { value: "Austria", label: "Austria" },
    { value: "Azerbaijan", label: "Azerbaijan" },
    { value: "Bahamas", label: "Bahamas" },
    { value: "Bahrain", label: "Bahrain" },
    { value: "Barbados", label: "Barbados" },
    { value: "Belarus", label: "Belarus" },
    { value: "Belgium", label: "Belgium" },
    { value: "Belize", label: "Belize" },
    { value: "Benin", label: "Benin" },
    { value: "Bhutan", label: "Bhutan" },
    { value: "Bolivia", label: "Bolivia" },
    { value: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina" },
    { value: "Botswana", label: "Botswana" },
    { value: "Brazil", label: "Brazil" },
    { value: "Brunei", label: "Brunei" },
    { value: "Bulgaria", label: "Bulgaria" },
    { value: "Burkina Faso", label: "Burkina Faso" },
    { value: "Burundi", label: "Burundi" },
    { value: "Cabo Verde", label: "Cabo Verde" },
    { value: "Cambodia", label: "Cambodia" },
    { value: "Cameroon", label: "Cameroon" },
    { value: "Canada", label: "Canada" },
    { value: "Central African Republic", label: "Central African Republic" },
    { value: "Chad", label: "Chad" },
    { value: "Chile", label: "Chile" },
    { value: "China", label: "China" },
    { value: "Colombia", label: "Colombia" },
    { value: "Comoros", label: "Comoros" },
    { value: "Congo", label: "Congo" },
    { value: "Costa Rica", label: "Costa Rica" },
    { value: "Croatia", label: "Croatia" },
    { value: "Cuba", label: "Cuba" },
    { value: "Cyprus", label: "Cyprus" },
    { value: "Czech Republic", label: "Czech Republic" },
    {
      value: "Democratic Republic of the Congo",
      label: "Democratic Republic of the Congo",
    },
    { value: "Denmark", label: "Denmark" },
    { value: "Djibouti", label: "Djibouti" },
    { value: "Dominica", label: "Dominica" },
    { value: "Dominican Republic", label: "Dominican Republic" },
    { value: "Ecuador", label: "Ecuador" },
    { value: "Egypt", label: "Egypt" },
    { value: "El Salvador", label: "El Salvador" },
    { value: "Equatorial Guinea", label: "Equatorial Guinea" },
    { value: "Eritrea", label: "Eritrea" },
    { value: "Estonia", label: "Estonia" },
    { value: "Eswatini", label: "Eswatini" },
    { value: "Ethiopia", label: "Ethiopia" },
    { value: "Fiji", label: "Fiji" },
    { value: "Finland", label: "Finland" },
    { value: "France", label: "France" },
    { value: "Gabon", label: "Gabon" },
    { value: "Gambia", label: "Gambia" },
    { value: "Georgia", label: "Georgia" },
    { value: "Germany", label: "Germany" },
    { value: "Ghana", label: "Ghana" },
    { value: "Greece", label: "Greece" },
    { value: "Grenada", label: "Grenada" },
    { value: "Guatemala", label: "Guatemala" },
    { value: "Guinea", label: "Guinea" },
    { value: "Guinea-Bissau", label: "Guinea-Bissau" },
    { value: "Guyana", label: "Guyana" },
    { value: "Haiti", label: "Haiti" },
    { value: "Honduras", label: "Honduras" },
    { value: "Hungary", label: "Hungary" },
    { value: "Iceland", label: "Iceland" },
    { value: "India", label: "India" },
    { value: "Indonesia", label: "Indonesia" },
    { value: "Iran", label: "Iran" },
    { value: "Iraq", label: "Iraq" },
    { value: "Ireland", label: "Ireland" },
    { value: "Israel", label: "Israel" },
    { value: "Italy", label: "Italy" },
    { value: "Ivory Coast", label: "Ivory Coast" },
    { value: "Jamaica", label: "Jamaica" },
    { value: "Japan", label: "Japan" },
    { value: "Jordan", label: "Jordan" },
    { value: "Kazakhstan", label: "Kazakhstan" },
    { value: "Kenya", label: "Kenya" },
    { value: "Kiribati", label: "Kiribati" },
    { value: "Kuwait", label: "Kuwait" },
    { value: "Kyrgyzstan", label: "Kyrgyzstan" },
    { value: "Laos", label: "Laos" },
    { value: "Latvia", label: "Latvia" },
    { value: "Lebanon", label: "Lebanon" },
    { value: "Lesotho", label: "Lesotho" },
    { value: "Liberia", label: "Liberia" },
    { value: "Libya", label: "Libya" },
    { value: "Liechtenstein", label: "Liechtenstein" },
    { value: "Lithuania", label: "Lithuania" },
    { value: "Luxembourg", label: "Luxembourg" },
    { value: "Madagascar", label: "Madagascar" },
    { value: "Malawi", label: "Malawi" },
    { value: "Malaysia", label: "Malaysia" },
    { value: "Maldives", label: "Maldives" },
    { value: "Mali", label: "Mali" },
    { value: "Malta", label: "Malta" },
    { value: "Marshall Islands", label: "Marshall Islands" },
    { value: "Mauritania", label: "Mauritania" },
    { value: "Mauritius", label: "Mauritius" },
    { value: "Mexico", label: "Mexico" },
    { value: "Micronesia", label: "Micronesia" },
    { value: "Moldova", label: "Moldova" },
    { value: "Monaco", label: "Monaco" },
    { value: "Mongolia", label: "Mongolia" },
    { value: "Montenegro", label: "Montenegro" },
    { value: "Morocco", label: "Morocco" },
    { value: "Mozambique", label: "Mozambique" },
    { value: "Myanmar", label: "Myanmar" },
    { value: "Namibia", label: "Namibia" },
    { value: "Nauru", label: "Nauru" },
    { value: "Nepal", label: "Nepal" },
    { value: "Netherlands", label: "Netherlands" },
    { value: "New Zealand", label: "New Zealand" },
    { value: "Nicaragua", label: "Nicaragua" },
    { value: "Niger", label: "Niger" },
    { value: "Nigeria", label: "Nigeria" },
    { value: "North Korea", label: "North Korea" },
    { value: "North Macedonia", label: "North Macedonia" },
    { value: "Norway", label: "Norway" },
    { value: "Oman", label: "Oman" },
    { value: "Pakistan", label: "Pakistan" },
    { value: "Palau", label: "Palau" },
    { value: "Palestine", label: "Palestine" },
    { value: "Panama", label: "Panama" },
    { value: "Papua New Guinea", label: "Papua New Guinea" },
    { value: "Paraguay", label: "Paraguay" },
    { value: "Peru", label: "Peru" },
    { value: "Philippines", label: "Philippines" },
    { value: "Poland", label: "Poland" },
    { value: "Portugal", label: "Portugal" },
    { value: "Qatar", label: "Qatar" },
    { value: "Romania", label: "Romania" },
    { value: "Russia", label: "Russia" },
    { value: "Rwanda", label: "Rwanda" },
    { value: "Saint Kitts and Nevis", label: "Saint Kitts and Nevis" },
    { value: "Saint Lucia", label: "Saint Lucia" },
    {
      value: "Saint Vincent and the Grenadines",
      label: "Saint Vincent and the Grenadines",
    },
    { value: "Samoa", label: "Samoa" },
    { value: "San Marino", label: "San Marino" },
    { value: "Sao Tome and Principe", label: "Sao Tome and Principe" },
    { value: "Saudi Arabia", label: "Saudi Arabia" },
    { value: "Senegal", label: "Senegal" },
    { value: "Serbia", label: "Serbia" },
    { value: "Seychelles", label: "Seychelles" },
    { value: "Sierra Leone", label: "Sierra Leone" },
    { value: "Singapore", label: "Singapore" },
    { value: "Slovakia", label: "Slovakia" },
    { value: "Slovenia", label: "Slovenia" },
    { value: "Solomon Islands", label: "Solomon Islands" },
    { value: "Somalia", label: "Somalia" },
    { value: "South Africa", label: "South Africa" },
    { value: "South Korea", label: "South Korea" },
    { value: "South Sudan", label: "South Sudan" },
    { value: "Spain", label: "Spain" },
    { value: "Sri Lanka", label: "Sri Lanka" },
    { value: "Sudan", label: "Sudan" },
    { value: "Suriname", label: "Suriname" },
    { value: "Sweden", label: "Sweden" },
    { value: "Switzerland", label: "Switzerland" },
    { value: "Syria", label: "Syria" },
    { value: "Taiwan", label: "Taiwan" },
    { value: "Tajikistan", label: "Tajikistan" },
    { value: "Tanzania", label: "Tanzania" },
    { value: "Thailand", label: "Thailand" },
    { value: "Timor-Leste", label: "Timor-Leste" },
    { value: "Togo", label: "Togo" },
    { value: "Tonga", label: "Tonga" },
    { value: "Trinidad and Tobago", label: "Trinidad and Tobago" },
    { value: "Tunisia", label: "Tunisia" },
    { value: "Turkey", label: "Turkey" },
    { value: "Turkmenistan", label: "Turkmenistan" },
    { value: "Tuvalu", label: "Tuvalu" },
    { value: "UAE", label: "UAE" },
    { value: "Uganda", label: "Uganda" },
    { value: "UK", label: "UK" },
    { value: "Ukraine", label: "Ukraine" },
    { value: "Uruguay", label: "Uruguay" },
    { value: "USA", label: "USA" },
    { value: "Uzbekistan", label: "Uzbekistan" },
    { value: "Vanuatu", label: "Vanuatu" },
    { value: "Vatican City", label: "Vatican City" },
    { value: "Venezuela", label: "Venezuela" },
    { value: "Vietnam", label: "Vietnam" },
    { value: "Yemen", label: "Yemen" },
    { value: "Zambia", label: "Zambia" },
    { value: "Zimbabwe", label: "Zimbabwe" },
    { value: "Other International", label: "Other International" },
  ],
};

// For compatibility with existing SearchProfiles.jsx
export const locationOptions = [
  { value: "", label: "Select District/Region" },
  { value: "Any", label: "Any District/Region" },

  // Dhaka Division
  { value: "Dhaka", label: "Dhaka", division: "Dhaka Division" },
  { value: "Faridpur", label: "Faridpur", division: "Dhaka Division" },
  { value: "Gazipur", label: "Gazipur", division: "Dhaka Division" },
  { value: "Gopalganj", label: "Gopalganj", division: "Dhaka Division" },
  { value: "Kishoreganj", label: "Kishoreganj", division: "Dhaka Division" },
  { value: "Madaripur", label: "Madaripur", division: "Dhaka Division" },
  { value: "Manikganj", label: "Manikganj", division: "Dhaka Division" },
  { value: "Munshiganj", label: "Munshiganj", division: "Dhaka Division" },
  { value: "Narayanganj", label: "Narayanganj", division: "Dhaka Division" },
  { value: "Narsingdi", label: "Narsingdi", division: "Dhaka Division" },
  { value: "Rajbari", label: "Rajbari", division: "Dhaka Division" },
  { value: "Shariatpur", label: "Shariatpur", division: "Dhaka Division" },
  { value: "Tangail", label: "Tangail", division: "Dhaka Division" },

  // Chittagong Division
  { value: "Chittagong", label: "Chittagong", division: "Chittagong Division" },
  { value: "Bandarban", label: "Bandarban", division: "Chittagong Division" },
  {
    value: "Brahmanbaria",
    label: "Brahmanbaria",
    division: "Chittagong Division",
  },
  { value: "Chandpur", label: "Chandpur", division: "Chittagong Division" },
  { value: "Comilla", label: "Comilla", division: "Chittagong Division" },
  {
    value: "Cox's Bazar",
    label: "Cox's Bazar",
    division: "Chittagong Division",
  },
  { value: "Feni", label: "Feni", division: "Chittagong Division" },
  {
    value: "Khagrachhari",
    label: "Khagrachhari",
    division: "Chittagong Division",
  },
  { value: "Lakshmipur", label: "Lakshmipur", division: "Chittagong Division" },
  { value: "Noakhali", label: "Noakhali", division: "Chittagong Division" },
  { value: "Rangamati", label: "Rangamati", division: "Chittagong Division" },

  // Rajshahi Division
  { value: "Rajshahi", label: "Rajshahi", division: "Rajshahi Division" },
  { value: "Bogra", label: "Bogra", division: "Rajshahi Division" },
  { value: "Joypurhat", label: "Joypurhat", division: "Rajshahi Division" },
  { value: "Naogaon", label: "Naogaon", division: "Rajshahi Division" },
  { value: "Natore", label: "Natore", division: "Rajshahi Division" },
  {
    value: "Chapainawabganj",
    label: "Chapainawabganj",
    division: "Rajshahi Division",
  },
  { value: "Pabna", label: "Pabna", division: "Rajshahi Division" },
  { value: "Sirajganj", label: "Sirajganj", division: "Rajshahi Division" },

  // Khulna Division
  { value: "Khulna", label: "Khulna", division: "Khulna Division" },
  { value: "Bagerhat", label: "Bagerhat", division: "Khulna Division" },
  { value: "Chuadanga", label: "Chuadanga", division: "Khulna Division" },
  { value: "Jessore", label: "Jessore", division: "Khulna Division" },
  { value: "Jhenaidah", label: "Jhenaidah", division: "Khulna Division" },
  { value: "Kushtia", label: "Kushtia", division: "Khulna Division" },
  { value: "Magura", label: "Magura", division: "Khulna Division" },
  { value: "Meherpur", label: "Meherpur", division: "Khulna Division" },
  { value: "Narail", label: "Narail", division: "Khulna Division" },
  { value: "Satkhira", label: "Satkhira", division: "Khulna Division" },

  // Barisal Division
  { value: "Barisal", label: "Barisal", division: "Barisal Division" },
  { value: "Barguna", label: "Barguna", division: "Barisal Division" },
  { value: "Bhola", label: "Bhola", division: "Barisal Division" },
  { value: "Jhalokati", label: "Jhalokati", division: "Barisal Division" },
  { value: "Patuakhali", label: "Patuakhali", division: "Barisal Division" },
  { value: "Pirojpur", label: "Pirojpur", division: "Barisal Division" },

  // Sylhet Division
  { value: "Sylhet", label: "Sylhet", division: "Sylhet Division" },
  { value: "Habiganj", label: "Habiganj", division: "Sylhet Division" },
  { value: "Moulvibazar", label: "Moulvibazar", division: "Sylhet Division" },
  { value: "Sunamganj", label: "Sunamganj", division: "Sylhet Division" },

  // Rangpur Division
  { value: "Rangpur", label: "Rangpur", division: "Rangpur Division" },
  { value: "Dinajpur", label: "Dinajpur", division: "Rangpur Division" },
  { value: "Gaibandha", label: "Gaibandha", division: "Rangpur Division" },
  { value: "Kurigram", label: "Kurigram", division: "Rangpur Division" },
  { value: "Lalmonirhat", label: "Lalmonirhat", division: "Rangpur Division" },
  { value: "Nilphamari", label: "Nilphamari", division: "Rangpur Division" },
  { value: "Panchagarh", label: "Panchagarh", division: "Rangpur Division" },
  { value: "Thakurgaon", label: "Thakurgaon", division: "Rangpur Division" },

  // Mymensingh Division
  { value: "Mymensingh", label: "Mymensingh", division: "Mymensingh Division" },
  { value: "Jamalpur", label: "Jamalpur", division: "Mymensingh Division" },
  { value: "Netrakona", label: "Netrakona", division: "Mymensingh Division" },
  { value: "Sherpur", label: "Sherpur", division: "Mymensingh Division" },

  // International
  { value: "Afghanistan", label: "Afghanistan", division: "International" },
  { value: "Albania", label: "Albania", division: "International" },
  { value: "Algeria", label: "Algeria", division: "International" },
  { value: "Andorra", label: "Andorra", division: "International" },
  { value: "Angola", label: "Angola", division: "International" },
  {
    value: "Antigua and Barbuda",
    label: "Antigua and Barbuda",
    division: "International",
  },
  { value: "Argentina", label: "Argentina", division: "International" },
  { value: "Armenia", label: "Armenia", division: "International" },
  { value: "Australia", label: "Australia", division: "International" },
  { value: "Austria", label: "Austria", division: "International" },
  { value: "Azerbaijan", label: "Azerbaijan", division: "International" },
  { value: "Bahamas", label: "Bahamas", division: "International" },
  { value: "Bahrain", label: "Bahrain", division: "International" },
  { value: "Barbados", label: "Barbados", division: "International" },
  { value: "Belarus", label: "Belarus", division: "International" },
  { value: "Belgium", label: "Belgium", division: "International" },
  { value: "Belize", label: "Belize", division: "International" },
  { value: "Benin", label: "Benin", division: "International" },
  { value: "Bhutan", label: "Bhutan", division: "International" },
  { value: "Bolivia", label: "Bolivia", division: "International" },
  {
    value: "Bosnia and Herzegovina",
    label: "Bosnia and Herzegovina",
    division: "International",
  },
  { value: "Botswana", label: "Botswana", division: "International" },
  { value: "Brazil", label: "Brazil", division: "International" },
  { value: "Brunei", label: "Brunei", division: "International" },
  { value: "Bulgaria", label: "Bulgaria", division: "International" },
  { value: "Burkina Faso", label: "Burkina Faso", division: "International" },
  { value: "Burundi", label: "Burundi", division: "International" },
  { value: "Cabo Verde", label: "Cabo Verde", division: "International" },
  { value: "Cambodia", label: "Cambodia", division: "International" },
  { value: "Cameroon", label: "Cameroon", division: "International" },
  { value: "Canada", label: "Canada", division: "International" },
  {
    value: "Central African Republic",
    label: "Central African Republic",
    division: "International",
  },
  { value: "Chad", label: "Chad", division: "International" },
  { value: "Chile", label: "Chile", division: "International" },
  { value: "China", label: "China", division: "International" },
  { value: "Colombia", label: "Colombia", division: "International" },
  { value: "Comoros", label: "Comoros", division: "International" },
  { value: "Congo", label: "Congo", division: "International" },
  { value: "Costa Rica", label: "Costa Rica", division: "International" },
  { value: "Croatia", label: "Croatia", division: "International" },
  { value: "Cuba", label: "Cuba", division: "International" },
  { value: "Cyprus", label: "Cyprus", division: "International" },
  {
    value: "Czech Republic",
    label: "Czech Republic",
    division: "International",
  },
  {
    value: "Democratic Republic of the Congo",
    label: "Democratic Republic of the Congo",
    division: "International",
  },
  { value: "Denmark", label: "Denmark", division: "International" },
  { value: "Djibouti", label: "Djibouti", division: "International" },
  { value: "Dominica", label: "Dominica", division: "International" },
  {
    value: "Dominican Republic",
    label: "Dominican Republic",
    division: "International",
  },
  { value: "Ecuador", label: "Ecuador", division: "International" },
  { value: "Egypt", label: "Egypt", division: "International" },
  { value: "El Salvador", label: "El Salvador", division: "International" },
  {
    value: "Equatorial Guinea",
    label: "Equatorial Guinea",
    division: "International",
  },
  { value: "Eritrea", label: "Eritrea", division: "International" },
  { value: "Estonia", label: "Estonia", division: "International" },
  { value: "Eswatini", label: "Eswatini", division: "International" },
  { value: "Ethiopia", label: "Ethiopia", division: "International" },
  { value: "Fiji", label: "Fiji", division: "International" },
  { value: "Finland", label: "Finland", division: "International" },
  { value: "France", label: "France", division: "International" },
  { value: "Gabon", label: "Gabon", division: "International" },
  { value: "Gambia", label: "Gambia", division: "International" },
  { value: "Georgia", label: "Georgia", division: "International" },
  { value: "Germany", label: "Germany", division: "International" },
  { value: "Ghana", label: "Ghana", division: "International" },
  { value: "Greece", label: "Greece", division: "International" },
  { value: "Grenada", label: "Grenada", division: "International" },
  { value: "Guatemala", label: "Guatemala", division: "International" },
  { value: "Guinea", label: "Guinea", division: "International" },
  { value: "Guinea-Bissau", label: "Guinea-Bissau", division: "International" },
  { value: "Guyana", label: "Guyana", division: "International" },
  { value: "Haiti", label: "Haiti", division: "International" },
  { value: "Honduras", label: "Honduras", division: "International" },
  { value: "Hungary", label: "Hungary", division: "International" },
  { value: "Iceland", label: "Iceland", division: "International" },
  { value: "India", label: "India", division: "International" },
  { value: "Indonesia", label: "Indonesia", division: "International" },
  { value: "Iran", label: "Iran", division: "International" },
  { value: "Iraq", label: "Iraq", division: "International" },
  { value: "Ireland", label: "Ireland", division: "International" },
  { value: "Israel", label: "Israel", division: "International" },
  { value: "Italy", label: "Italy", division: "International" },
  { value: "Ivory Coast", label: "Ivory Coast", division: "International" },
  { value: "Jamaica", label: "Jamaica", division: "International" },
  { value: "Japan", label: "Japan", division: "International" },
  { value: "Jordan", label: "Jordan", division: "International" },
  { value: "Kazakhstan", label: "Kazakhstan", division: "International" },
  { value: "Kenya", label: "Kenya", division: "International" },
  { value: "Kiribati", label: "Kiribati", division: "International" },
  { value: "Kuwait", label: "Kuwait", division: "International" },
  { value: "Kyrgyzstan", label: "Kyrgyzstan", division: "International" },
  { value: "Laos", label: "Laos", division: "International" },
  { value: "Latvia", label: "Latvia", division: "International" },
  { value: "Lebanon", label: "Lebanon", division: "International" },
  { value: "Lesotho", label: "Lesotho", division: "International" },
  { value: "Liberia", label: "Liberia", division: "International" },
  { value: "Libya", label: "Libya", division: "International" },
  { value: "Liechtenstein", label: "Liechtenstein", division: "International" },
  { value: "Lithuania", label: "Lithuania", division: "International" },
  { value: "Luxembourg", label: "Luxembourg", division: "International" },
  { value: "Madagascar", label: "Madagascar", division: "International" },
  { value: "Malawi", label: "Malawi", division: "International" },
  { value: "Malaysia", label: "Malaysia", division: "International" },
  { value: "Maldives", label: "Maldives", division: "International" },
  { value: "Mali", label: "Mali", division: "International" },
  { value: "Malta", label: "Malta", division: "International" },
  {
    value: "Marshall Islands",
    label: "Marshall Islands",
    division: "International",
  },
  { value: "Mauritania", label: "Mauritania", division: "International" },
  { value: "Mauritius", label: "Mauritius", division: "International" },
  { value: "Mexico", label: "Mexico", division: "International" },
  { value: "Micronesia", label: "Micronesia", division: "International" },
  { value: "Moldova", label: "Moldova", division: "International" },
  { value: "Monaco", label: "Monaco", division: "International" },
  { value: "Mongolia", label: "Mongolia", division: "International" },
  { value: "Montenegro", label: "Montenegro", division: "International" },
  { value: "Morocco", label: "Morocco", division: "International" },
  { value: "Mozambique", label: "Mozambique", division: "International" },
  { value: "Myanmar", label: "Myanmar", division: "International" },
  { value: "Namibia", label: "Namibia", division: "International" },
  { value: "Nauru", label: "Nauru", division: "International" },
  { value: "Nepal", label: "Nepal", division: "International" },
  { value: "Netherlands", label: "Netherlands", division: "International" },
  { value: "New Zealand", label: "New Zealand", division: "International" },
  { value: "Nicaragua", label: "Nicaragua", division: "International" },
  { value: "Niger", label: "Niger", division: "International" },
  { value: "Nigeria", label: "Nigeria", division: "International" },
  { value: "North Korea", label: "North Korea", division: "International" },
  {
    value: "North Macedonia",
    label: "North Macedonia",
    division: "International",
  },
  { value: "Norway", label: "Norway", division: "International" },
  { value: "Oman", label: "Oman", division: "International" },
  { value: "Pakistan", label: "Pakistan", division: "International" },
  { value: "Palau", label: "Palau", division: "International" },
  { value: "Palestine", label: "Palestine", division: "International" },
  { value: "Panama", label: "Panama", division: "International" },
  {
    value: "Papua New Guinea",
    label: "Papua New Guinea",
    division: "International",
  },
  { value: "Paraguay", label: "Paraguay", division: "International" },
  { value: "Peru", label: "Peru", division: "International" },
  { value: "Philippines", label: "Philippines", division: "International" },
  { value: "Poland", label: "Poland", division: "International" },
  { value: "Portugal", label: "Portugal", division: "International" },
  { value: "Qatar", label: "Qatar", division: "International" },
  { value: "Romania", label: "Romania", division: "International" },
  { value: "Russia", label: "Russia", division: "International" },
  { value: "Rwanda", label: "Rwanda", division: "International" },
  {
    value: "Saint Kitts and Nevis",
    label: "Saint Kitts and Nevis",
    division: "International",
  },
  { value: "Saint Lucia", label: "Saint Lucia", division: "International" },
  {
    value: "Saint Vincent and the Grenadines",
    label: "Saint Vincent and the Grenadines",
    division: "International",
  },
  { value: "Samoa", label: "Samoa", division: "International" },
  { value: "San Marino", label: "San Marino", division: "International" },
  {
    value: "Sao Tome and Principe",
    label: "Sao Tome and Principe",
    division: "International",
  },
  { value: "Saudi Arabia", label: "Saudi Arabia", division: "International" },
  { value: "Senegal", label: "Senegal", division: "International" },
  { value: "Serbia", label: "Serbia", division: "International" },
  { value: "Seychelles", label: "Seychelles", division: "International" },
  { value: "Sierra Leone", label: "Sierra Leone", division: "International" },
  { value: "Singapore", label: "Singapore", division: "International" },
  { value: "Slovakia", label: "Slovakia", division: "International" },
  { value: "Slovenia", label: "Slovenia", division: "International" },
  {
    value: "Solomon Islands",
    label: "Solomon Islands",
    division: "International",
  },
  { value: "Somalia", label: "Somalia", division: "International" },
  { value: "South Africa", label: "South Africa", division: "International" },
  { value: "South Korea", label: "South Korea", division: "International" },
  { value: "South Sudan", label: "South Sudan", division: "International" },
  { value: "Spain", label: "Spain", division: "International" },
  { value: "Sri Lanka", label: "Sri Lanka", division: "International" },
  { value: "Sudan", label: "Sudan", division: "International" },
  { value: "Suriname", label: "Suriname", division: "International" },
  { value: "Sweden", label: "Sweden", division: "International" },
  { value: "Switzerland", label: "Switzerland", division: "International" },
  { value: "Syria", label: "Syria", division: "International" },
  { value: "Taiwan", label: "Taiwan", division: "International" },
  { value: "Tajikistan", label: "Tajikistan", division: "International" },
  { value: "Tanzania", label: "Tanzania", division: "International" },
  { value: "Thailand", label: "Thailand", division: "International" },
  { value: "Timor-Leste", label: "Timor-Leste", division: "International" },
  { value: "Togo", label: "Togo", division: "International" },
  { value: "Tonga", label: "Tonga", division: "International" },
  {
    value: "Trinidad and Tobago",
    label: "Trinidad and Tobago",
    division: "International",
  },
  { value: "Tunisia", label: "Tunisia", division: "International" },
  { value: "Turkey", label: "Turkey", division: "International" },
  { value: "Turkmenistan", label: "Turkmenistan", division: "International" },
  { value: "Tuvalu", label: "Tuvalu", division: "International" },
  { value: "UAE", label: "UAE", division: "International" },
  { value: "Uganda", label: "Uganda", division: "International" },
  { value: "UK", label: "UK", division: "International" },
  { value: "Ukraine", label: "Ukraine", division: "International" },
  { value: "Uruguay", label: "Uruguay", division: "International" },
  { value: "USA", label: "USA", division: "International" },
  { value: "Uzbekistan", label: "Uzbekistan", division: "International" },
  { value: "Vanuatu", label: "Vanuatu", division: "International" },
  { value: "Vatican City", label: "Vatican City", division: "International" },
  { value: "Venezuela", label: "Venezuela", division: "International" },
  { value: "Vietnam", label: "Vietnam", division: "International" },
  { value: "Yemen", label: "Yemen", division: "International" },
  { value: "Zambia", label: "Zambia", division: "International" },
  { value: "Zimbabwe", label: "Zimbabwe", division: "International" },
  {
    value: "Other International",
    label: "Other International",
    division: "International",
  },
];

// Group locations by division for easier rendering (for backward compatibility)
export const locationsByDivision = {
  "": [
    { value: "", label: "Select District/Region" },
    { value: "Any", label: "Any District/Region" },
  ],
  "Dhaka Division": locationOptions.filter(
    (loc) => loc.division === "Dhaka Division"
  ),
  "Chittagong Division": locationOptions.filter(
    (loc) => loc.division === "Chittagong Division"
  ),
  "Rajshahi Division": locationOptions.filter(
    (loc) => loc.division === "Rajshahi Division"
  ),
  "Khulna Division": locationOptions.filter(
    (loc) => loc.division === "Khulna Division"
  ),
  "Barisal Division": locationOptions.filter(
    (loc) => loc.division === "Barisal Division"
  ),
  "Sylhet Division": locationOptions.filter(
    (loc) => loc.division === "Sylhet Division"
  ),
  "Rangpur Division": locationOptions.filter(
    (loc) => loc.division === "Rangpur Division"
  ),
  "Mymensingh Division": locationOptions.filter(
    (loc) => loc.division === "Mymensingh Division"
  ),
  International: locationOptions.filter(
    (loc) => loc.division === "International"
  ),
};
